[package]
name = "nft-mint"
version = "0.1.0"
authors = ["Khubaib Ishtiaq <khubaibahmedishtiaq@gmail.co>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"